export default colors = {
    primary: '#FDE93A',
    danger: '#ff424a',
    success: '#6fc276',
    light: '#ffffff',
    backgroundDefault: 'black',
    loadingLayer: 'rgba(0, 0, 0, 0.6)',
    defaultText: '#ffffff',
    textLight: '#ffffff',
    textDark: '#000000',
    textHighlight: '#FDE93A',
    textDanger: '#c9002c',
    cardBackground: '#000000',
    cardBorder: '#ffffff',
};